---
- name: Disable swap and update /etc/fstab to prevent swap from being enabled on boot
  hosts: k8s_control_plane, k8s_worker
  become: yes  # This is equivalent to using sudo
  tasks:
    - name: Disable all swap spaces immediately
      ansible.builtin.command:
        cmd: swapoff -a
      changed_when: false  # This tells Ansible not to consider the task as a change
    
    - name: Comment out swap entry in /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^(.+\sswap\s.+)$'
        line: '#\1'
        backrefs: yes
