---
- name: Configure Kubernetes prerequisites
  hosts: all
  become: yes
  tasks:
    - name: Ensure the overlay and br_netfilter modules are loaded
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
      notify: Load modules

    - name: Set sysctl parameters for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
      notify: Reload sysctl

  handlers:
    - name: Load modules
      ansible.builtin.command:
        cmd: modprobe {{ item }}
      loop:
        - overlay
        - br_netfilter
      # Ensuring idempotence: Run only if the module is not already loaded
      when: ansible_facts['kernel_modules'][item] is not defined

    - name: Reload sysctl
      ansible.builtin.command:
        cmd: sysctl --system
      ignore_errors: yes