---
- name: Install Docker on Ubuntu
  hosts: self, k8s_control_plane, k8s_worker
  become: true
  vars:
    dist: "{{ ansible_distribution_release | lower }}"
  tasks:
    - name: Remove deprecated and conflicting packages
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent
    - name: Update apt cache and install required packages
      apt:
        update_cache: true
        autoremove: true
        name:
          - ca-certificates
          - curl
        state: present
    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 'a+r'
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ dist }} stable"
        state: present
        filename: docker
    - name: Update apt and install Docker
      apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
