---
- name: Update /etc/hosts file
  hosts: all
  become: yes
  tasks:
    - name: Ensure entries are present in /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
        regexp: '^(\s*{{ item.split()[0] }})\s+{{ item.split()[1] }}.*$'
      loop:
        - "192.168.35.190  ubuntu-ha-proxy"
        - "192.168.35.191  ubuntu-master-1"
        - "192.168.35.192  ubuntu-master-2"
        - "192.168.35.193  ubuntu-slave-1"
        - "192.168.35.194  ubuntu-slave-2"
        - "192.168.35.195  ubuntu-ceph-1"
        - "192.168.35.196  ubuntu-ceph-2"
        - "192.168.35.197  ubuntu-ceph-3"
