---
- hosts: self
  become: true
  tasks:
    - name: Update, Upgrade, and Autoclean
      apt:
        update_cache: true
        upgrade: true
        autoremove: true
        autoclean: true
        purge: true
