---
- name: Configure Ceph repository and perform dist-upgrade
  hosts: all
  become: true  # Use sudo for the tasks
  tasks:
    - name: Download Ceph release key
      get_url:
        url: https://download.ceph.com/keys/release.asc
        dest: /tmp/ceph-release.asc
        mode: '0644'
    - name: Add Ceph release key
      shell: gpg --dearmor < /tmp/ceph-release.asc > /etc/apt/trusted.gpg.d/ceph-keyring.gpg
      args:
        executable: /bin/bash
        creates: /etc/apt/trusted.gpg.d/ceph-keyring.gpg
      become: true
      changed_when: false
    - name: Add Ceph repository
      apt_repository:
        repo: 'deb https://download.ceph.com/debian-reef/ jammy main'
        state: present
    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true
        cache_valid_time: 3600
